"""Write the trip files the site reads (docs/TRIP-DATA.md) and a human report."""

import datetime as dt
import json
from pathlib import Path
from xml.sax.saxutils import escape

import numpy as np

from .geo import LocalProjection, rdp_indices

DETAIL_ONLY = ("path", "turnaround_index", "marking_runs", "parking_alternatives", "transit_alternatives", "pois")
ATTRIBUTION = ("© OpenStreetMap contributors (ODbL); elevation: Copernicus DEM GLO-30 © DLR e.V. 2010-2014 and "
               "© Airbus Defence and Space GmbH 2014-2018 provided under COPERNICUS by the European Union and ESA")


def write(root, trips, dem, drive, slugs, report, osm_data_at, now=None):
    root = Path(root)
    now = now or dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    trips = sorted(trips, key=lambda t: (t["region"], -t["rank"], t["slug"]))
    tdir = root / "data" / "trips"
    gdir = root / "public" / "gpx"
    tdir.mkdir(parents=True, exist_ok=True)
    gdir.mkdir(parents=True, exist_ok=True)
    keep = {t["slug"] for t in trips}
    for f in tdir.glob("*.json"):
        if f.name != "index.json" and f.stem not in keep:
            f.unlink()
    for f in gdir.glob("*.gpx"):
        if f.stem not in keep:
            f.unlink()

    summaries = []
    for t in trips:
        gpx = t.pop("_gpx")
        (gdir / f"{t['slug']}.gpx").write_text(_gpx(t["name"], gpx, dem))
        (tdir / f"{t['slug']}.json").write_text(json.dumps(t, ensure_ascii=False, separators=(",", ":")) + "\n")
        summaries.append({k: v for k, v in t.items() if k not in DETAIL_ONLY})

    index = dict(version=1, generated_at=now, osm_data_at=osm_data_at, attribution=ATTRIBUTION, trips=summaries)
    (tdir / "index.json").write_text(json.dumps(index, ensure_ascii=False, indent=1) + "\n")

    lines = [
        "// Generated by pipeline/publish.py. Do not edit by hand.",
        'import type { TripDetail } from "@/lib/tripSchema";',
        "",
        "type Loader = () => Promise<TripDetail>;",
        "const load = (p: Promise<{ default: unknown }>) => p.then((m) => m.default as TripDetail);",
        "",
        "export const tripDetailLoaders: Record<string, Loader> = {",
        *[f'  "{t["slug"]}": () => load(import("./{t["slug"]}.json")),' for t in trips],
        "};",
        "",
    ]
    (tdir / "details.generated.ts").write_text("\n".join(lines))

    if drive is not None:
        towns, minutes, km, source = drive
        (root / "data" / "drive-times.json").write_text(json.dumps(dict(
            version=1, generated_at=now, source=source, towns=towns, slugs=[t["slug"] for t in trips],
            minutes=minutes, km=km), ensure_ascii=False, separators=(",", ":")) + "\n")

    (root / "pipeline" / "slugs.json").write_text(json.dumps(dict(sorted(slugs.items())), ensure_ascii=False, indent=1) + "\n")
    (root / "data" / "pipeline-report.md").write_text(_report(trips, report, now, osm_data_at, drive))


def _gpx(name, g, dem):
    lat, lon, _ele, _rt, turn, loop = g
    lat, lon = np.asarray(lat), np.asarray(lon)
    if not loop:
        lat = np.concatenate([lat[: turn + 1], lat[:turn][::-1]])
        lon = np.concatenate([lon[: turn + 1], lon[:turn][::-1]])
    keep = rdp_indices(LocalProjection().xy(lat, lon), 2.0)
    lat, lon = lat[keep], lon[keep]
    ele = dem.sample(lat, lon) if dem else np.full(len(lat), np.nan)
    n = escape(name)
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<gpx version="1.1" creator="MounTour (OpenStreetMap)" xmlns="http://www.topografix.com/GPX/1/1">',
           f'  <metadata><name>{n}</name><copyright author="OpenStreetMap contributors"><license>https://opendatacommons.org/licenses/odbl/</license></copyright></metadata>',
           f"  <trk><name>{n}</name><trkseg>"]
    for la, lo, e in zip(lat, lon, ele):
        out.append(f'    <trkpt lat="{la:.6f}" lon="{lo:.6f}">' + (f"<ele>{e:.0f}</ele>" if np.isfinite(e) else "") + "</trkpt>")
    out += ["  </trkseg></trk>", "</gpx>", ""]
    return "\n".join(out)


def _report(trips, rep, now, osm_at, drive):
    L = [f"# Trip pipeline report", "", f"Run: {now} · OSM data: {osm_at or 'unknown'}", "",
         f"**{len(trips)} trips**", "", "| Region | Trips | Family | Candidates |", "|---|---|---|---|"]
    for rid, r in rep["regions"].items():
        fam = sum(1 for t in trips if t["region"] == rid and t["family_friendly"])
        n = sum(1 for t in trips if t["region"] == rid)
        L.append(f"| {rid} | {n} | {fam} | {r['candidates']} |")
    L += ["", "## Regression: the 10 hand-picked trips vs. the 2026-10-07 build", "",
          "Flag ⚠ when off by more than 15 %.", "",
          "| Trip | Distance (new / old) | Ascent | Time |", "|---|---|---|---|"]
    for r in rep["regression"]:
        if "error" in r:
            L.append(f"| {r['slug']} | ❌ {r['error']} | | |")
            continue
        cells = []
        for k in ("distance_m", "ascent_m", "duration_min"):
            if k in r:
                new, old, d = r[k]
                cells.append(f"{new} / {old} ({d:+.0%}){' ⚠' if abs(d) > 0.15 else ''}")
            else:
                cells.append("")
        L.append(f"| {r['slug']} | " + " | ".join(cells) + " |")
    L += ["", "## Rejected candidates", ""] + [f"- {k}: {v}" for k, v in sorted(rep["rejected"].items())]
    if rep.get("unresolved"):
        L += ["", "## Rule place names not found in OSM (check spelling in the rule files)", ""]
        L += [f"- {rid}: {', '.join(names)}" for rid, names in rep["unresolved"].items()]
    L += ["", "## Trips", "", "| Slug | Region | Start | km | ↑ m | Time | Diff. | Rules |", "|---|---|---|---|---|---|---|---|"]
    for t in trips:
        rules = ", ".join(t["closure_rule_ids"] + [f["rule_id"] or "osm fee" for f in t["fees"]])
        L.append(f"| {t['slug']} | {t['region']} | {t['start']['name']} | {t['distance_m'] / 1000:.1f} | "
                 f"{t['ascent_m']} | {t['duration_min'] // 60}:{t['duration_min'] % 60:02d} | {t['difficulty']} | {rules} |")
    if drive is not None:
        towns, minutes, _km, _ = drive
        missing = sum(1 for row in minutes for v in row if v is None)
        L += ["", f"Drive table: {len(towns)} towns x {len(trips)} trips, {missing} pairs without a route."]
    return "\n".join(L) + "\n"
