// Generated by pipeline/publish.py. Do not edit by hand.
import type { TripDetail } from "@/lib/tripSchema";

type Loader = () => Promise<TripDetail>;
const load = (p: Promise<{ default: unknown }>) => p.then((m) => m.default as TripDetail);

export const tripDetailLoaders: Record<string, Loader> = {
  "devinska-kobyla": () => load(import("./devinska-kobyla.json")),
  "kamzik": () => load(import("./kamzik.json")),
  "biely-kriz": () => load(import("./biely-kriz.json")),
  "pajstun": () => load(import("./pajstun.json")),
  "vysoka": () => load(import("./vysoka.json")),
  "velka-homola": () => load(import("./velka-homola.json")),
  "zaruby": () => load(import("./zaruby.json")),
  "plavecky-hrad": () => load(import("./plavecky-hrad.json")),
  "cerveny-kamen": () => load(import("./cerveny-kamen.json")),
  "cachticky-hrad": () => load(import("./cachticky-hrad.json")),
};
